FROM python:3.8.10-slim

RUN useradd logger


WORKDIR /home/logger

COPY requirements.txt requirements.txt
RUN python3 -m venv venv
RUN python3 --version
RUN venv/bin/pip install --upgrade pip==20.0.2
RUN venv/bin/pip install -r requirements.txt

COPY app app
COPY migrations migrations
COPY logger.py config.py ./
RUN chmod +x boot.sh

ENV FLASK_APP logger.py
ENV SETUP_STATUS 0

RUN chown -R logger:logger ./
USER logger

EXPOSE 5000