FROM python:3.8.10-slim

RUN useradd logger


WORKDIR /home/logger

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt


COPY app app
COPY migrations migrations
COPY logger.py config.py ./
RUN flask db upgrade

ENV FLASK_APP=logger.py
# ENV SETUP_STATUS=0

RUN chown -R logger:logger ./
USER logger

EXPOSE 5000